added products db model
2209-FSA-ginger/GraceShopperProject pull request #3
Opened 2022-11-08 23:08 UTC by p-mcgrath

2022-11-08 23:14 UTC, ariadosic requested changes
good job :)

2022-11-08 23:14 UTC, ariadosic commented on server/db/models/Product.js
> +    type: Sequelize.FLOAT,
Sequelize.Decimal(10,2) ???

2022-11-08 23:14 UTC, ariadosic commented on server/db/models/Product.js
> +    type: Sequelize.FLOAT,
Sequelize.Decimal(10,2) ???

2022-11-09 15:17 UTC, p-mcgrath commented on server/db/models/Product.js
> +    type: Sequelize.FLOAT,
fixed

2022-11-09 15:36 UTC, ariadosic approved these changes

2022-11-09 15:38 UTC, merged